services:
  postgres:
    image: timescale/timescaledb:latest-pg16  
    environment:
      POSTGRES_USER: sb
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smartbov                  
    ports:
      - "5432:5432"
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d 
  broker:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
