version: "3.8"
services:
  postgres:
    image: timescale/timescaledb:pg16-latest
    environment:
      POSTGRES_USER: sb
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  broker:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
